const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const multer = require('multer');
const { uploadDir } = require('../db');

const MAX_BYTES = 2 * 1024 * 1024;
const EXT_BY_MIME = { 'image/png': '.png', 'image/jpeg': '.jpg', 'image/webp': '.webp' };

const upload = multer({
  storage: multer.diskStorage({
    destination: uploadDir,
    filename: (req, file, cb) =>
      cb(null, crypto.randomBytes(16).toString('hex') + EXT_BY_MIME[file.mimetype]),
  }),
  limits: { fileSize: MAX_BYTES, files: 1, fields: 12, fieldSize: 5000 },
  fileFilter: (req, file, cb) => {
    if (EXT_BY_MIME[file.mimetype]) return cb(null, true);
    cb(new Error('BAD_TYPE'));
  },
}).single('avatar');

/**
 * Runs multer and stores a friendly message on req.uploadError instead of
 * throwing, so the form can re-render with the user's other fields intact.
 */
function handleAvatarUpload(req, res, next) {
  upload(req, res, (err) => {
    if (err) {
      req.uploadError =
        err.code === 'LIMIT_FILE_SIZE'
          ? 'Image must be 2 MB or smaller.'
          : err.message === 'BAD_TYPE'
          ? 'Use a PNG, JPG, or WebP image.'
          : 'The upload failed. Try a different image.';
    }
    next();
  });
}

/** The declared MIME type is client-controlled, so check the real file header. */
function looksLikeImage(filePath) {
  let fd;
  try {
    fd = fs.openSync(filePath, 'r');
    const head = Buffer.alloc(12);
    fs.readSync(fd, head, 0, 12, 0);
    const isPng = head.subarray(0, 4).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47]));
    const isJpg = head.subarray(0, 3).equals(Buffer.from([0xff, 0xd8, 0xff]));
    const isWebp =
      head.subarray(0, 4).toString('ascii') === 'RIFF' &&
      head.subarray(8, 12).toString('ascii') === 'WEBP';
    return isPng || isJpg || isWebp;
  } catch {
    return false;
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }
}

function removeAvatarFile(filename) {
  if (!filename) return;
  // Filenames are generated by us, but never trust a path read from the DB blindly.
  fs.unlink(path.join(uploadDir, path.basename(filename)), () => {});
}

module.exports = { handleAvatarUpload, looksLikeImage, removeAvatarFile };
